import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/componants/Header";
import Footer from "@/componants/Footer";

const poppins = Poppins({ subsets: ["latin"], weight:['100','200','300','400','500','600','700','800','900'] });

export const metadata = {
  title: "Medicon-Group",
  description: "Generated by Next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
          <Header />
          {children}
          <Footer/>
      </body>
    </html>
  );
}
